apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: spring-boot
  labels:
    app: spring-boot-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: spring-boot-deployment
      labels:
        app: spring-boot-deployment
    spec:
      containers:
        - name: spring-boot-deployment
          image: yudady/k8s:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-boot-deployment
